// Transactions
export const SET_FILTER = 'SET_FILTER';
export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export const UPDATE_TRANSACTION_CATEGORY_INFO = 'UPDATE_TRANSACTION_CATEGORY_INFO';
export const SPLIT_TRANSACTION = 'SPLIT_TRANSACTION';
export const UNSPLIT_TRANSACTION = 'UNSPLIT_TRANSACTION';

// Rules
export const GET_RULES = 'GET_RULES';
export const TOGGLE_RULE_MODAL = 'TOGGLE_RULE_MODAL';
export const RULE_ADD = 'RULE_ADD';
export const RULE_EDIT = 'RULE_EDIT';
export const RULE_SUBMIT_CREATE = 'RULE_SUBMIT_CREATE';
export const RULE_SUBMIT_UPDATE = 'RULE_SUBMIT_UPDATE';
export const RULES_DELETE = 'RULES_DELETE';

// Statistics
export const GET_CHART_DATA = 'GET_CHART_DATA';
export const CHART_DATA_LOADING = 'CHART_DATA_LOADING';
export const SET_STATISTICS_FILTER = 'SET_STATISTICS_FILTER';

// Bank accounts
export const GET_BANK_ACCOUNTS = 'GET_BANK_ACCOUNTS';

// Shared
export const DATA_LOADING = 'DATA_LOADING';
